@startuml azabugakuen_info
!startsub INFO
  最寄駅 => 白金高輪
  通学時間 => 60分
  学食 => 有り
  自転車通学 => NG
  男子校
!endsub INFO
@enduml


@startuml azabugakuen_test
map 麻布学園 {
  申込開始 => 2021/11/01
  申込締切 => 2021/11/30
  受験日 => 2022/02/01
  偏差値 => 65
  !includesub azabu.puml!INFO
}
@enduml